version: 2
jobs:
  build:
    working_directory: ~/tesseract.js
    docker:
      - image: circleci/node:10.15.0
    environment:
      - NPM_CONFIG_LOGLEVEL=warn
    steps:
      - checkout
      - restore_cache:
          key: npm-dependency-cache-{{ checksum "package-lock.json" }}
      - run:
          name: Install dependencies
          command: npm install
      - save_cache:
          key: npm-dependency-cache-{{ checksum "package-lock.json" }}
          paths:
            - node_modules
      - run:
          name: Build
          command: npm run build
      - run:
          name: Linting
          command: npm run lint
      - run:
          name: Unit testing
          command: |
            npm run test
      - store_artifacts:
          path: dist